### ISSUE TITLE
Request to bring back Metube 

### ISSUE THREAD

**Issue by z8512** [wy580477/Colab-Heroku-AIO-APP-EX#11]
Metube was very helpful. It downloads in mp4/mkv format.
Yt-dlp us hard to use since it is cli. Metube was very easy

Thank you

**Comment by wy580477** [comment]
You can add following to config.yaml file under config/olivetin folder.

 ```
  - title: yt-dlp to mp4 & auto-upload to Rclone remote
    icon: "&#128316;"
    shell: ytdlpup.sh {{ urls }} {{ options }} -f mp4
    timeout: 36000
    arguments:
      - name: urls
        type: very_dangerous_raw_string
      - name: options
        type: very_dangerous_raw_string
 ```

This will add a action to OliveTin WebUI. Then you can use this action to download videos as mp4 format.

I know it's not as pretty as metube, but this way is more flexible. You can create different actions for any yt-dlp options you want.
